#!/usr/bin/env bash
# git-checkout-ours.sh — Resolve conflicts by checking out the "ours" side.
#
# Wraps `git checkout --ours -- <files>`. During rebase, `--ours` means the
# base being rebased ONTO (i.e., upstream main). /implement's Conflict
# Resolution Procedure uses this for trivial files like
# `.claude-plugin/plugin.json` that will be regenerated by the re-bump step.
#
# Usage:
#   git-checkout-ours.sh <file> [<file> ...]
#
# Exit codes: passthrough from `git checkout`.

set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "git-checkout-ours.sh: at least one file argument is required" >&2
    echo "usage: git-checkout-ours.sh <file> [<file> ...]" >&2
    exit 1
fi

exec git checkout --ours -- "$@"
